---
- name: Configure nginx web server
  hosts: ansibletest
  tasks:
  - name: install nginx server
    yum:
      name: nginx
      state: present
      update_cache: true
  - service:
      name: nginx
      state: started
    become: true