---
- name: Configure nginx web server
  hosts: ansibletest
  tasks:
  - name: install nginx server
    yum:
      name: nginx
      state: latest
      update_cache: yes
      upgrade: yes
  - service:
      name: nginx
      state: started