---
- name: Configure nginx web server
  hosts: ansibletest
  tasks:
  - name: add the /etc/yum.repos.d/epel.repo
    yum_repository:
      name: epel
      description: EPEL repo
      baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
  - name: install nginx server
    yum:
      name: nginx
      state: latest
  - service:
      name: nginx
      state: started