---
- name: Configure nginx web server
  hosts: ansibletest
  become: true
  tasks:
  - name: install nginx
    yum:
      name: nginx
      gpgkey: http://nginx.org/packages/keys/nginx_signing.key
      state: present
  - name: start nginx
    service:
      name: nginx
      state: started
    