---
- name: Configure nginx web server
  hosts: ansibletest
  tasks:
  - name: update yum cache
    yum:
        update_cache: yes
        upgrade: yes
  - name: install nginx server
    yum:
      name: nginx
      state: latest
  - service:
      name: nginx
      state: started